import { testSuite } from "@previewjs/app/testing";

export const actionLogsTests = testSuite("Pro: action logs", (test) => {
  test(
    "shows action logs on autogenerated callback prop",
    "samples/default",
    async ({ appDir, controller }) => {
      await appDir.update("src/Button.tsx", {
        kind: "replace",
        text: `
function Button(props: { label: string; onClick(): void }) {
  return (
    <button id="button" onClick={props.onClick}>
      {props.label}
    </button>
  );
}
`,
      });
      await controller.show("src/Button.tsx:Button");
      const previewIframe = await controller.previewIframe();
      await previewIframe.waitForSelector("#button");
      await previewIframe.click("#button");
      const actionLog = await controller.actionLog.get(
        "Function prop invoked: onClick"
      );
      await actionLog.waitUntilVisible();
      await actionLog.waitUntilGone();
    }
  );
});
