packages:
  - "api"
  - "app"
  - "app-foundations"
  - "cli"
  - "config"
  - "core"
  - "csf3"
  - "dev-workspace"
  - "e2e-test-runner"
  - "frameworks/*"
  - "frameworks/*/preview"
  - "iframe"
  - "integrations/intellij/controller"
  - "integrations/vscode"
  - "loader"
  - "serializable-values"
  - "server"
  - "test-apps/*"
  - "!test-apps/_tmp_*"
  - "smoke-test-apps/*"
  - "!smoke-test-apps/_tmp_*"
  - "type-analyzer"
  - "vfs"
