packages:
  - "api"
  - "app"
  - "cli"
  - "config"
  - "core"
  - "dev-workspace"
  - "frameworks/*"
  - "frameworks/*/preview"
  - "integrations/intellij/controller"
  - "integrations/vscode"
  - "loader"
  - "pro"
  - "test-apps/*"
  - "!test-apps/_tmp_*"
  - "smoke-test-apps/*"
  - "!smoke-test-apps/_tmp_*"
  - "type-analyzer"
  - "vfs"
