packages:
  - "api"
  - "app"
  - "chromeless"
  - "config"
  - "core"
  - "config-helpers/*"
  - "csf3"
  - "daemon"
  - "dev-workspace"
  - "frameworks/*"
  - "frameworks/*/preview"
  - "frameworks/*/tests/apps/*"
  - "iframe"
  - "integrations/cli"
  - "integrations/intellij/daemon"
  - "integrations/vscode"
  - "loader"
  - "!loader/src/*"
  - "properties"
  - "serializable-values"
  - "testing"
  - "type-analyzer"
  - "vfs"
