packages:
  - "api"
  - "app"
  - "chromeless"
  - "component-test"
  - "component-test/test-app"
  - "config"
  - "core"
  - "analyzer/*"
  - "config-helpers/*"
  - "daemon"
  - "dev-workspace"
  - "framework-plugins/*"
  - "framework-plugins/*/preview"
  - "framework-plugins/*/tests/apps/*"
  - "iframe"
  - "integrations/cli"
  - "integrations/intellij/daemon"
  - "integrations/vscode"
  - "loader"
  - "!loader/src/*"
  - "properties"
  - "screenshot"
  - "screenshot/test-app"
  - "serializable-values"
  - "storybook-helpers"
  - "testing"
  - "type-analyzer"
  - "vfs"
