name: "\U0001F41E Bug report (CLI)"
description: Report an issue with Preview.js CLI
labels: [pending triage, cli]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      description: Steps to reproduce the behavior. Bonus points if you can point to a repository that exhibits the issue!
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: previewjs-version
    attributes:
      label: Preview.js CLI version
      description: Version number of Preview.js CLI (`previewjs -V`)
      placeholder: v1.0.0
    validations:
      required: true
  - type: input
    id: framework
    attributes:
      label: Framework
      description: Which framework are you using? Please include version as well.
      placeholder: React 18.0.0
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --binaries --ides --browsers`
      render: shell
      placeholder: System, Binaries, IDEs, Browsers
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Used Package Manager
      description: Select the package manager you use in your project
      options:
        - npm
        - yarn
        - pnpm
    validations:
      required: true
  - type: textarea
    attributes:
      label: CLI logs (useful for crashes)
      render: shell
  - type: textarea
    attributes:
      label: Browser logs (useful for rendering errors)
      render: shell
  - type: textarea
    attributes:
      label: Repo link (if available)
      description: |
        It can be significantly easier to fix a bug when a repo is available to reproduce it :)
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? Screenshots? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
