name: Release Components

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 18.x
      - name: Cache pnpm modules
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-exclude-test-apps-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-exclude-test-apps-
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          run_install: |
            - args: [--filter=\!./framework-plugins/\*/tests/apps/\*]
      - name: Update NPM token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - run: pnpm turbo build --filter="!./integrations/**/*" --filter="!./daemon"
      - run: |
          cd api
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd app
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd chromeless
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd analyzer/api
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd analyzer/react
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd config
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd config-helpers/nextjs
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd core
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd iframe
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd framework-plugins/preact
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd framework-plugins/react
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd framework-plugins/solid
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd framework-plugins/svelte
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd framework-plugins/vue2
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd framework-plugins/vue3
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd properties
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd serializable-values
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd screenshot
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd storybook-helpers
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd testing
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd type-analyzer
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd vfs
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
