name: Release @previewjs/plugin-vue3

on:
  release:
    types:
      - created

defaults:
  run:
    working-directory: frameworks/vue3

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/plugins/vue3/v')
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: ${{ matrix.node-version }}
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.3.0
          run_install: true
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2.2.1
        id: version
        with:
          cmd: "jq .version frameworks/vue3/package.json -r"
      - name: Extract version from release name
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/plugins\/vue3\/v/}" >> $GITHUB_ENV
      - name: Check that versions match
        run: '[[ "${{ steps.version.outputs.value }}" == "$VERSION" ]] && echo "Versions match"'
      - name: Publish
        run: pnpm publish --no-git-checks --access public
