name: Release VS Code Extension

on:
  release:
    types:
      - created

defaults:
  run:
    working-directory: integrations/vscode

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/integrations/vscode/v')
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.24.4
          run_install: true
      - run: cd .. && pnpm turbo run build --scope=@previewjs/loader --no-deps --include-dependencies
      - run: yarn --frozen-lockfile
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2.1.0
        id: version
        with:
          cmd: "jq .version integrations/vscode/package.json -r"
      - name: Extract version from release name
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/integrations\/vscode\/v/}" >> $GITHUB_ENV
      - name: Check that versions match
        run: '[[ "${{ steps.version.outputs.value }}" == "$VERSION" ]] && echo "Versions match"'
      - name: Publish to Visual Studio Code Marketplace
        run: yarn vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - name: Publish to Open VSX Registry
        run: yarn ovsx publish -p $OVSX_TOKEN
        env:
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
