name: Release Components

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-exclude-test-apps-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-exclude-test-apps-
      - uses: pnpm/action-setup@v2.2.4
        with:
          run_install: |
            - args: [--filter=\!./frameworks/\*/tests/apps/\*]
      - name: Update NPM token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - run: pnpm turbo build --filter="!./integrations/**/*" --filter="!./daemon"
      - run: |
          cd api
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd app
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd chromeless
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd config
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd config-helpers/nextjs
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd core
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd iframe
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd frameworks/preact
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd frameworks/react
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd frameworks/solid
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd frameworks/svelte
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd frameworks/vue2
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd frameworks/vue3
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd properties
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd serializable-values
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd storybook-helpers
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd testing
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd type-analyzer
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
      - run: |
          cd vfs
          if ! pnpm publish --no-git-checks --access public 2>error.log; then
            if grep -q -F 'You cannot publish over the previously published versions' error.log; then
              echo "Package is already published. Ignoring the following:"
              cat error.log
            else
              cat error.log >&2
              exit 1
            fi
          fi
