name: Release @previewjs/cli

on:
  release:
    types:
      - created

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/cli/v')
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          always-auth: true
          node-version: ${{ matrix.node-version }}
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Cache pnpm modules
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-exclude-test-apps-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-exclude-test-apps-
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          run_install: |
            - args: [--filter=\!./framework-plugins/\*/tests/apps/\*]
      - run: pnpm turbo build --filter="./integrations/cli"
      - name: Extract version from package.json
        uses: sergeysova/jq-action@a3f0d4ff59cc1dddf023fc0b325dd75b10deec58 # v2.3.0
        id: version
        with:
          cmd: "jq .version integrations/cli/package.json -r"
      - name: Extract version from release name
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/cli\/v/}" >> $GITHUB_ENV
      - name: Check that versions match
        run: '[[ "${{ steps.version.outputs.value }}" == "$VERSION" ]] && echo "Versions match"'
      - name: Publish
        run: cd integrations/cli && pnpm publish --no-git-checks --access public
