name: Test Vite Ecosystem CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - "**"
      - ".github/workflows/test-vite-ecosystem-ci.yaml"
      - "!assets/**"
      - "!integrations/**"
  pull_request:
    branches:
      - "*"
    paths:
      - "**"
      - ".github/workflows/test-vite-ecosystem-ci.yaml"
      - "!assets/**"
      - "!integrations/**"

jobs:
  vite-ecosystem-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache pnpm modules
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-full-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-full-
      - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          run_install: true
      - run: pnpm update -r vite@beta
      - run: cd testing && pnpm exec playwright install
      - run: pnpm vite-ecosystem-ci:build
      - run: pnpm vite-ecosystem-ci:test
