name: IntelliJ tests

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - "integrations/intellij/**"
      - ".github/workflows/test-intellij.yaml"
  pull_request:
    branches:
      - "*"
    paths:
      - "integrations/intellij/**"
      - ".github/workflows/test-intellij.yaml"

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - run: pnpm turbo run build --scope="@previewjs/loader" --include-dependencies --no-deps
      - run: cd integrations/intellij && cd controller && pnpm build && cd .. && ./gradlew buildPlugin
