name: Preview.js core tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!assets/**"
      - "!cli/**"
      - "!integrations/**"
  pull_request:
    branches:
      - "*"
    paths:
      - "**"
      - "!assets/**"
      - "!cli/**"
      - "!integrations/**"

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.4
          run_install: true
      # - run: yarn licenses-check
      - run: pnpm turbo run build --scope="@previewjs/app" --include-dependencies
      - run: cd type-analyzer && pnpm test
      - run: cd core && pnpm test
      - run: cd frameworks/react && pnpm test
      - run: cd app && pnpm lint && pnpm test
